CREATE TABLE IF NOT EXISTS category (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(500),
  description TEXT,
  slug VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS under_category (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(500),
  description TEXT,
  slug VARCHAR(255) UNIQUE NOT NULL,
  category_id INTEGER REFERENCES category(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS post (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(500),
  description TEXT,
  slug VARCHAR(255) UNIQUE NOT NULL,
  under_category_id INTEGER REFERENCES under_category(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS post_details (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(500),
  description TEXT,
  slug VARCHAR(255) UNIQUE NOT NULL,
  post_id INTEGER REFERENCES post(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
