import Script from "next/script";

export default function Head() {
    return (
      <>
        <title>Categories | MatheMatiques Du Secondaire</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5587331919297301"
     crossOrigin="anonymous" strategy="lazyOnload" />
        <link rel="icon" href="/favicon.ico" />
      </>
    );
  }