export default function Head() {
  return (
    <>
      <title>MatheMatiques Du Secondaire</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
        rel="stylesheet"
      />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
